[2024-02-01T09:06:18.850+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: hola_mundo.branch_task manual__2024-02-01T09:03:08.311646+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
