[2024-02-26T08:33:37.527+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: hola_mundo.print_bye_task scheduled__2024-02-02T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
