[2024-02-26T08:33:37.837+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: hola_mundo.branch_b scheduled__2024-02-06T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
