[2024-02-01T08:39:22.239+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: hola_mundo.print_hello_task manual__2024-02-01T08:39:05.197095+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
