[2024-01-31T12:04:32.932+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:04:32.934+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:04:32.938+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:04:32.938+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:04:33.001+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:04:34.025+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:04:34.023+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:hola_mundo
[2024-01-31T12:04:34.054+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:04:34.053+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:hola_mundo
[2024-01-31T12:04:34.075+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:04:34.074+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:hola_mundo
[2024-01-31T12:04:34.076+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:04:34.076+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:04:34.108+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:04:34.108+0000] {dag.py:3058} INFO - Creating ORM DAG for hola_mundo
[2024-01-31T12:04:34.140+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:04:34.140+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-01 00:00:00+00:00, run_after=2024-01-02 00:00:00+00:00
[2024-01-31T12:04:34.200+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 1.292 seconds
[2024-01-31T12:05:04.800+0000] {processor.py:161} INFO - Started process (PID=92) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:05:04.807+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:05:04.874+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:05:04.866+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:05:04.921+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:05:05.263+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:05:05.262+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:05:05.523+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:05:05.522+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-01 00:00:00+00:00, run_after=2024-01-02 00:00:00+00:00
[2024-01-31T12:05:05.675+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.898 seconds
[2024-01-31T12:05:45.120+0000] {processor.py:161} INFO - Started process (PID=126) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:05:45.124+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:05:45.132+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:05:45.131+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:05:45.154+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:05:45.259+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:05:45.259+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:05:45.478+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:05:45.477+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-01 00:00:00+00:00, run_after=2024-01-02 00:00:00+00:00
[2024-01-31T12:05:45.986+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.877 seconds
[2024-01-31T12:06:17.650+0000] {processor.py:161} INFO - Started process (PID=180) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:06:17.656+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:06:17.671+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:06:17.670+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:06:17.714+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:06:17.844+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:06:17.843+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:06:17.951+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:06:17.950+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-01 00:00:00+00:00, run_after=2024-01-02 00:00:00+00:00
[2024-01-31T12:06:18.040+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.409 seconds
[2024-01-31T12:07:05.383+0000] {processor.py:161} INFO - Started process (PID=235) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:07:05.406+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:07:05.427+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:07:05.425+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:07:05.736+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:07:36.886+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 859, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 895, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 657, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 670, in _sync_to_db
    _serialize_dag_capturing_errors(dag, session, processor_subdir)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 635, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-01-31T12:08:07.727+0000] {processor.py:161} INFO - Started process (PID=291) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:08:07.737+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:08:07.741+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:08:07.740+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:08:07.768+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:08:07.857+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:08:07.854+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:08:07.933+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:08:07.933+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-01 00:00:00+00:00, run_after=2024-01-02 00:00:00+00:00
[2024-01-31T12:08:08.018+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.304 seconds
[2024-01-31T12:10:02.673+0000] {processor.py:161} INFO - Started process (PID=341) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:10:02.698+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:10:02.732+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:10:02.699+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:10:03.272+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:10:36.229+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 859, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 895, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 657, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 670, in _sync_to_db
    _serialize_dag_capturing_errors(dag, session, processor_subdir)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 635, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-01-31T12:13:18.797+0000] {processor.py:161} INFO - Started process (PID=387) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:13:18.810+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:13:18.817+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:13:18.811+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:13:18.896+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:13:58.711+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 859, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 895, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 657, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 670, in _sync_to_db
    _serialize_dag_capturing_errors(dag, session, processor_subdir)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 635, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/serialized_dag.py", line 157, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-01-31T12:14:32.245+0000] {processor.py:161} INFO - Started process (PID=401) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:14:32.264+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:14:32.266+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:14:32.265+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:14:32.287+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:14:33.243+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:14:33.242+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:14:33.349+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:14:33.347+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-02 00:00:00+00:00, run_after=2024-01-03 00:00:00+00:00
[2024-01-31T12:14:33.463+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 1.233 seconds
[2024-01-31T12:24:04.694+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:24:04.699+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:24:04.709+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:24:04.708+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:24:04.814+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:24:06.060+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:24:06.059+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:24:06.299+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 1.623 seconds
[2024-01-31T12:25:51.957+0000] {processor.py:161} INFO - Started process (PID=96) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:25:52.046+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:25:52.051+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:25:52.050+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:25:52.527+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:25:53.593+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:25:53.572+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:26:05.056+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 13.137 seconds
[2024-01-31T12:26:51.159+0000] {processor.py:161} INFO - Started process (PID=101) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:26:51.174+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:26:51.243+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:26:51.242+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:26:51.931+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:26:53.565+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:26:53.564+0000] {taskinstance.py:2700} ERROR - {'DAG Id': 'hola_mundo', 'Task Id': 'print_hello_task', 'Run Id': 'scheduled__2024-01-08T00:00:00+00:00', 'Hostname': '60382a02b079', 'External Executor Id': 'ee6491d4-08a6-400b-b0c5-4b8f7645d3b1'}
[2024-01-31T12:26:54.265+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:26:54.264+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=hola_mundo, task_id=print_hello_task, execution_date=20240108T000000, start_date=20240131T122611, end_date=20240131T122653
[2024-01-31T12:26:54.825+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: hola_mundo.print_hello_task scheduled__2024-01-08T00:00:00+00:00 [failed]> in state failed
[2024-01-31T12:26:54.845+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:26:54.845+0000] {taskinstance.py:2700} ERROR - {'DAG Id': 'hola_mundo', 'Task Id': 'print_hello_task', 'Run Id': 'scheduled__2024-01-12T00:00:00+00:00', 'Hostname': '60382a02b079', 'External Executor Id': 'a65fdb34-bb27-4bff-b254-49d6eec5230b'}
[2024-01-31T12:26:55.038+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:26:54.989+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=hola_mundo, task_id=print_hello_task, execution_date=20240112T000000, start_date=20240131T122612, end_date=20240131T122654
[2024-01-31T12:26:55.096+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: hola_mundo.print_hello_task scheduled__2024-01-12T00:00:00+00:00 [failed]> in state failed
[2024-01-31T12:27:01.381+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:27:01.381+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:27:01.722+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:27:01.713+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-18 00:00:00+00:00, run_after=2024-01-19 00:00:00+00:00
[2024-01-31T12:27:01.852+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 10.776 seconds
[2024-01-31T12:28:28.606+0000] {processor.py:161} INFO - Started process (PID=163) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:28:28.615+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:28:28.618+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:28:28.617+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:28:28.657+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:28:28.758+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:28:28.757+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:28:28.884+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:28:28.884+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-23 00:00:00+00:00, run_after=2024-01-24 00:00:00+00:00
[2024-01-31T12:28:28.981+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.391 seconds
[2024-01-31T12:28:36.565+0000] {processor.py:161} INFO - Started process (PID=190) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:28:36.567+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:28:36.580+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:28:36.579+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:28:36.739+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:28:37.159+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:28:37.158+0000] {taskinstance.py:2700} ERROR - {'DAG Id': 'hola_mundo', 'Task Id': 'print_hello_task', 'Run Id': 'scheduled__2024-01-14T00:00:00+00:00', 'Hostname': '60382a02b079', 'External Executor Id': '7c5ad8a0-42d8-4a58-b252-9cf73743bbfd'}
[2024-01-31T12:28:37.555+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:28:37.541+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=hola_mundo, task_id=print_hello_task, execution_date=20240114T000000, start_date=20240131T122652, end_date=20240131T122837
[2024-01-31T12:28:37.661+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: hola_mundo.print_hello_task scheduled__2024-01-14T00:00:00+00:00 [failed]> in state failed
[2024-01-31T12:28:37.699+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:28:37.698+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:28:37.785+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:28:37.784+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-24 00:00:00+00:00, run_after=2024-01-25 00:00:00+00:00
[2024-01-31T12:28:37.899+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 1.357 seconds
[2024-01-31T12:29:21.542+0000] {processor.py:161} INFO - Started process (PID=208) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:29:21.552+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:29:21.555+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:29:21.554+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:29:21.599+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:29:22.033+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:29:22.032+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:29:22.618+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:29:22.616+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-25 00:00:00+00:00, run_after=2024-01-26 00:00:00+00:00
[2024-01-31T12:29:22.786+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 1.267 seconds
[2024-01-31T12:32:45.840+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:32:45.848+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:32:45.854+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:32:45.853+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:32:45.977+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:32:46.985+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:32:46.985+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:32:47.044+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:32:47.043+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-26 00:00:00+00:00, run_after=2024-01-27 00:00:00+00:00
[2024-01-31T12:32:47.116+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 1.299 seconds
[2024-01-31T12:32:56.575+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:32:56.579+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:32:56.596+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:32:56.591+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:32:56.614+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:32:56.746+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:32:56.745+0000] {taskinstance.py:2700} ERROR - {'DAG Id': 'hola_mundo', 'Task Id': 'print_hello_task', 'Run Id': 'scheduled__2024-01-20T00:00:00+00:00', 'Hostname': '60382a02b079', 'External Executor Id': '703ddee2-c42f-439a-84dd-d6a841d9801c'}
[2024-01-31T12:32:57.085+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:32:57.084+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=hola_mundo, task_id=print_hello_task, execution_date=20240120T000000, start_date=20240131T122847, end_date=20240131T123256
[2024-01-31T12:32:57.406+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: hola_mundo.print_hello_task scheduled__2024-01-20T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2024-01-31T12:32:57.423+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:32:57.422+0000] {taskinstance.py:2700} ERROR - {'DAG Id': 'hola_mundo', 'Task Id': 'print_hello_task', 'Run Id': 'scheduled__2024-01-21T00:00:00+00:00', 'Hostname': '60382a02b079', 'External Executor Id': '3778fea0-f6c1-49b8-87d7-6be226af0ee7'}
[2024-01-31T12:32:57.465+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:32:57.465+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=hola_mundo, task_id=print_hello_task, execution_date=20240121T000000, start_date=20240131T122847, end_date=20240131T123257
[2024-01-31T12:32:57.486+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: hola_mundo.print_hello_task scheduled__2024-01-21T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2024-01-31T12:32:57.495+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:32:57.494+0000] {taskinstance.py:2700} ERROR - {'DAG Id': 'hola_mundo', 'Task Id': 'print_hello_task', 'Run Id': 'scheduled__2024-01-22T00:00:00+00:00', 'Hostname': '60382a02b079', 'External Executor Id': '9c1fb06f-f6cf-4d9e-b8f8-cd08aea66985'}
[2024-01-31T12:32:57.523+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:32:57.521+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=hola_mundo, task_id=print_hello_task, execution_date=20240122T000000, start_date=20240131T122847, end_date=20240131T123257
[2024-01-31T12:32:57.531+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: hola_mundo.print_hello_task scheduled__2024-01-22T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2024-01-31T12:32:57.587+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:32:57.587+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:32:57.672+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:32:57.671+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T12:32:57.716+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 1.150 seconds
[2024-01-31T12:33:36.766+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:33:36.779+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:33:36.805+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:33:36.795+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:33:36.875+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:33:51.319+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:33:51.319+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:33:51.469+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:33:51.468+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T12:33:51.605+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 14.871 seconds
[2024-01-31T12:34:50.440+0000] {processor.py:161} INFO - Started process (PID=145) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:34:50.448+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:34:50.455+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:34:50.454+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:34:50.475+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:34:50.523+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:34:50.522+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:34:50.591+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:34:50.590+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T12:34:50.647+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.214 seconds
[2024-01-31T12:35:22.967+0000] {processor.py:161} INFO - Started process (PID=201) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:35:22.975+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:35:22.980+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:35:22.978+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:35:22.995+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:35:23.060+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:35:23.059+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:35:23.128+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:35:23.127+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T12:35:23.175+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.221 seconds
[2024-01-31T12:35:53.897+0000] {processor.py:161} INFO - Started process (PID=255) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:35:53.900+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:35:53.904+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:35:53.903+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:35:53.919+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:35:53.961+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:35:53.961+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:35:54.012+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:35:54.011+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T12:35:54.050+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.163 seconds
[2024-01-31T12:36:24.337+0000] {processor.py:161} INFO - Started process (PID=311) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:36:24.343+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:36:24.350+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:36:24.349+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:36:24.363+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:36:24.403+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:36:24.403+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:36:24.450+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:36:24.450+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T12:36:24.495+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.166 seconds
[2024-01-31T12:36:54.685+0000] {processor.py:161} INFO - Started process (PID=367) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:36:54.689+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:36:54.694+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:36:54.693+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:36:54.709+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:36:54.866+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:36:54.864+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:36:54.967+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:36:54.966+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T12:36:55.059+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.385 seconds
[2024-01-31T12:39:41.853+0000] {processor.py:161} INFO - Started process (PID=386) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:39:41.886+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:39:41.888+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:39:41.887+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:39:42.958+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:45:45.545+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:45:45.553+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:45:45.557+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:45:45.556+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:45:45.601+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:45:46.227+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:45:46.226+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:45:46.298+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:45:46.297+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T12:45:46.360+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.821 seconds
[2024-01-31T12:46:16.404+0000] {processor.py:161} INFO - Started process (PID=92) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:46:16.408+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:46:16.414+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:46:16.413+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:46:16.428+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:46:16.476+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:46:16.476+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:46:16.535+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:46:16.534+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T12:46:16.590+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.194 seconds
[2024-01-31T12:46:47.108+0000] {processor.py:161} INFO - Started process (PID=149) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:46:47.127+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:46:47.134+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:46:47.133+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:46:47.215+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:46:47.383+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:46:47.383+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:46:47.598+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:46:47.597+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T12:46:47.794+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.695 seconds
[2024-01-31T12:47:18.174+0000] {processor.py:161} INFO - Started process (PID=205) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:47:18.177+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:47:18.182+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:47:18.181+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:47:18.204+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:47:18.315+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:47:18.315+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:47:18.414+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:47:18.413+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T12:47:18.492+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.325 seconds
[2024-01-31T12:47:49.375+0000] {processor.py:161} INFO - Started process (PID=259) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:47:49.378+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:47:49.382+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:47:49.382+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:47:49.400+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:47:49.437+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:47:49.436+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:47:49.492+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:47:49.491+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T12:47:49.541+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.180 seconds
[2024-01-31T12:48:19.835+0000] {processor.py:161} INFO - Started process (PID=315) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:48:19.841+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:48:19.844+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:48:19.843+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:48:19.875+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:48:20.190+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:48:20.189+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:48:20.302+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:48:20.298+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T12:48:20.375+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.558 seconds
[2024-01-31T12:48:51.056+0000] {processor.py:161} INFO - Started process (PID=370) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:48:51.061+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:48:51.066+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:48:51.065+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:48:51.083+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:48:51.139+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:48:51.139+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:48:51.210+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:48:51.210+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T12:48:51.260+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.212 seconds
[2024-01-31T12:49:35.615+0000] {processor.py:161} INFO - Started process (PID=396) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:49:35.623+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:49:35.628+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:49:35.626+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:49:35.652+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:49:35.709+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:49:35.708+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:49:35.842+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:49:35.842+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T12:49:35.944+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.360 seconds
[2024-01-31T12:50:07.173+0000] {processor.py:161} INFO - Started process (PID=452) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:50:07.189+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:50:07.197+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:50:07.196+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:50:07.231+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:50:07.367+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:50:07.366+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:50:07.537+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:50:07.534+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T12:50:07.653+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.491 seconds
[2024-01-31T12:50:38.384+0000] {processor.py:161} INFO - Started process (PID=507) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:50:38.401+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:50:38.406+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:50:38.405+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:50:38.427+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:50:38.492+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:50:38.490+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:50:38.565+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:50:38.564+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T12:50:38.640+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.272 seconds
[2024-01-31T12:51:09.367+0000] {processor.py:161} INFO - Started process (PID=563) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:51:09.373+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:51:09.380+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:51:09.379+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T12:51:09.407+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T12:51:09.512+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:51:09.511+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T12:51:09.759+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:51:09.759+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T12:51:09.940+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.587 seconds
[2024-01-31T12:57:35.333+0000] {processor.py:161} INFO - Started process (PID=609) to work on /opt/airflow/dags/prueba.py
[2024-01-31T12:57:49.546+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T12:58:34.998+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:58:24.410+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:00:11.549+0000] {logging_mixin.py:188} INFO - [2024-01-31T12:59:35.111+0000] {timeout.py:68} ERROR - Process timed out, PID: 609
[2024-01-31T13:06:43.461+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:00:52.749+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 33, in <module>
    hello_task = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 445, in apply_defaults
    self.set_xcomargs_dependencies()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1159, in set_xcomargs_dependencies
    XComArg.apply_upstream_relationship(self, arg)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 128, in apply_upstream_relationship
    for operator, _ in XComArg.iter_xcom_references(arg):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 116, in iter_xcom_references
    elif isinstance(arg, AbstractOperator):
  File "/usr/local/lib/python3.8/abc.py", line 98, in __instancecheck__
    return _abc_instancecheck(cls, instance)
  File "/usr/local/lib/python3.8/abc.py", line 102, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
  File "/usr/local/lib/python3.8/abc.py", line 102, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
  File "/usr/local/lib/python3.8/abc.py", line 102, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
  [Previous line repeated 1 more time]
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/prueba.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.8.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.8.1/best-practices.html#reducing-dag-complexity, PID: 609
[2024-01-31T13:07:37.969+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:27:51.867+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:27:51.873+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:27:51.877+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:27:51.876+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:27:52.023+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:27:53.067+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:27:53.066+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:27:53.154+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:27:53.154+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:27:53.260+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 1.400 seconds
[2024-01-31T13:28:26.802+0000] {processor.py:161} INFO - Started process (PID=95) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:28:26.816+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:28:26.820+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:28:26.819+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:28:26.855+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:28:26.966+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:28:26.966+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:28:27.101+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:28:27.100+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:28:27.179+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.388 seconds
[2024-01-31T13:28:59.458+0000] {processor.py:161} INFO - Started process (PID=151) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:28:59.460+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:28:59.473+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:28:59.473+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:28:59.494+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:28:59.592+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:28:59.591+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:28:59.732+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:28:59.719+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:28:59.874+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.434 seconds
[2024-01-31T13:29:30.889+0000] {processor.py:161} INFO - Started process (PID=205) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:29:30.912+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:29:30.922+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:29:30.915+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:29:30.937+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:29:31.137+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:29:31.137+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:29:31.274+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:29:31.273+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:29:31.397+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.561 seconds
[2024-01-31T13:30:01.952+0000] {processor.py:161} INFO - Started process (PID=260) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:30:01.966+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:30:01.980+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:30:01.969+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:30:02.028+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:30:02.185+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:30:02.184+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:30:02.390+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:30:02.389+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:30:02.531+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.599 seconds
[2024-01-31T13:30:33.095+0000] {processor.py:161} INFO - Started process (PID=316) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:30:33.157+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:30:33.161+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:30:33.160+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:30:33.194+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:30:33.313+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:30:33.312+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:30:33.487+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:30:33.476+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:30:33.625+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.548 seconds
[2024-01-31T13:31:04.037+0000] {processor.py:161} INFO - Started process (PID=372) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:31:04.040+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:31:04.044+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:31:04.043+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:31:04.055+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:31:04.098+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:31:04.098+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:31:04.151+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:31:04.150+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:31:04.197+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.168 seconds
[2024-01-31T13:31:34.742+0000] {processor.py:161} INFO - Started process (PID=427) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:31:34.751+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:31:34.756+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:31:34.755+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:31:34.776+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:31:34.845+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:31:34.845+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:31:34.927+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:31:34.926+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:31:35.021+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.291 seconds
[2024-01-31T13:32:05.338+0000] {processor.py:161} INFO - Started process (PID=477) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:32:05.340+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:32:05.345+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:32:05.344+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:32:05.359+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:32:05.419+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:32:05.419+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:32:05.564+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:32:05.563+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:32:05.618+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.288 seconds
[2024-01-31T13:32:37.094+0000] {processor.py:161} INFO - Started process (PID=531) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:32:37.102+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:32:37.106+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:32:37.105+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:32:37.133+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:32:37.229+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:32:37.228+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:32:37.333+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:32:37.332+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:32:37.458+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.372 seconds
[2024-01-31T13:33:07.764+0000] {processor.py:161} INFO - Started process (PID=587) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:33:07.766+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:33:07.770+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:33:07.770+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:33:07.789+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:33:07.909+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:33:07.908+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:33:08.081+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:33:08.080+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:33:08.223+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.476 seconds
[2024-01-31T13:33:38.417+0000] {processor.py:161} INFO - Started process (PID=642) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:33:38.420+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:33:38.426+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:33:38.425+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:33:38.442+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:33:38.525+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:33:38.524+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:33:38.661+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:33:38.660+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:33:38.827+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.422 seconds
[2024-01-31T13:34:08.969+0000] {processor.py:161} INFO - Started process (PID=698) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:34:08.972+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:34:08.975+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:34:08.974+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:34:08.985+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:34:09.029+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:34:09.028+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:34:09.070+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:34:09.069+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:34:09.102+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.139 seconds
[2024-01-31T13:34:39.739+0000] {processor.py:161} INFO - Started process (PID=754) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:34:39.745+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:34:39.749+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:34:39.748+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:34:39.767+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:34:39.819+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:34:39.818+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:34:39.879+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:34:39.879+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:34:39.933+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.201 seconds
[2024-01-31T13:35:10.045+0000] {processor.py:161} INFO - Started process (PID=805) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:35:10.052+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:35:10.059+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:35:10.056+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:35:10.106+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:35:10.206+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:35:10.205+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:35:10.375+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:35:10.375+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:35:10.481+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.452 seconds
[2024-01-31T13:35:40.930+0000] {processor.py:161} INFO - Started process (PID=861) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:35:40.932+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:35:40.935+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:35:40.935+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:35:40.946+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:35:40.994+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:35:40.993+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:35:41.049+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:35:41.048+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:35:41.115+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.192 seconds
[2024-01-31T13:36:12.025+0000] {processor.py:161} INFO - Started process (PID=917) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:36:12.034+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:36:12.037+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:36:12.037+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:36:12.049+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:36:12.088+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:36:12.087+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:36:12.132+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:36:12.132+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:36:12.182+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.171 seconds
[2024-01-31T13:36:42.221+0000] {processor.py:161} INFO - Started process (PID=973) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:36:42.223+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:36:42.227+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:36:42.226+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:36:42.246+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:36:42.293+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:36:42.292+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:36:42.345+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:36:42.345+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:36:42.384+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.170 seconds
[2024-01-31T13:37:12.482+0000] {processor.py:161} INFO - Started process (PID=1029) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:37:12.486+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:37:12.489+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:37:12.489+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:37:12.502+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:37:12.552+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:37:12.551+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:37:12.634+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:37:12.633+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:37:12.726+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.251 seconds
[2024-01-31T13:37:42.871+0000] {processor.py:161} INFO - Started process (PID=1085) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:37:42.873+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:37:42.877+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:37:42.876+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:37:42.892+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:37:42.947+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:37:42.945+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:37:43.016+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:37:43.015+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:37:43.071+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.207 seconds
[2024-01-31T13:38:13.179+0000] {processor.py:161} INFO - Started process (PID=1138) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:38:13.185+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:38:13.188+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:38:13.188+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:38:13.198+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:38:13.241+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:38:13.240+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:38:13.298+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:38:13.297+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:38:13.342+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.172 seconds
[2024-01-31T13:38:43.663+0000] {processor.py:161} INFO - Started process (PID=1192) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:38:43.666+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:38:43.670+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:38:43.669+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:38:43.679+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:38:43.719+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:38:43.719+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:38:43.770+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:38:43.769+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:38:43.841+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.183 seconds
[2024-01-31T13:39:14.492+0000] {processor.py:161} INFO - Started process (PID=1247) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:39:14.496+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:39:14.500+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:39:14.499+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:39:14.513+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:39:14.574+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:39:14.573+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:39:14.631+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:39:14.630+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:39:14.671+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.192 seconds
[2024-01-31T13:39:45.468+0000] {processor.py:161} INFO - Started process (PID=1303) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:39:45.477+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:39:45.481+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:39:45.480+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:39:45.493+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:39:45.539+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:39:45.538+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:39:45.652+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:39:45.646+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:39:45.708+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.249 seconds
[2024-01-31T13:40:15.943+0000] {processor.py:161} INFO - Started process (PID=1360) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:40:15.952+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:40:15.956+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:40:15.955+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:40:15.967+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:40:16.012+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:40:16.012+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:40:16.073+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:40:16.072+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:40:16.115+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.180 seconds
[2024-01-31T13:40:46.513+0000] {processor.py:161} INFO - Started process (PID=1416) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:40:46.516+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:40:46.520+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:40:46.519+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:40:46.532+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:40:46.578+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:40:46.577+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:40:46.642+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:40:46.641+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:40:46.691+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.183 seconds
[2024-01-31T13:41:17.398+0000] {processor.py:161} INFO - Started process (PID=1472) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:41:17.400+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:41:17.415+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:41:17.404+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:41:17.449+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:41:17.590+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:41:17.589+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:41:17.807+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:41:17.806+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:41:17.938+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.553 seconds
[2024-01-31T13:41:48.098+0000] {processor.py:161} INFO - Started process (PID=1528) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:41:48.109+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:41:48.114+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:41:48.113+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:41:48.148+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:41:48.197+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:41:48.197+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:41:48.268+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:41:48.268+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:41:48.315+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.237 seconds
[2024-01-31T13:42:18.383+0000] {processor.py:161} INFO - Started process (PID=1584) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:42:18.386+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:42:18.390+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:42:18.389+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:42:18.401+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:42:18.445+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:42:18.444+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:42:18.502+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:42:18.502+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:42:18.549+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.173 seconds
[2024-01-31T13:42:48.695+0000] {processor.py:161} INFO - Started process (PID=1640) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:42:48.699+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:42:48.709+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:42:48.708+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:42:48.726+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:42:48.798+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:42:48.797+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:42:48.929+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:42:48.917+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:42:49.056+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.374 seconds
[2024-01-31T13:43:19.150+0000] {processor.py:161} INFO - Started process (PID=1698) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:43:19.152+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:43:19.155+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:43:19.154+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:43:19.163+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:43:19.197+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:43:19.197+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:43:19.243+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:43:19.242+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:43:19.280+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.136 seconds
[2024-01-31T13:43:49.397+0000] {processor.py:161} INFO - Started process (PID=1754) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:43:49.402+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:43:49.406+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:43:49.405+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:43:49.424+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:43:49.574+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:43:49.571+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:43:49.674+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:43:49.673+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:43:49.793+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.413 seconds
[2024-01-31T13:44:34.789+0000] {processor.py:161} INFO - Started process (PID=1804) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:44:34.803+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:44:34.821+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:44:34.808+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:44:34.899+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:44:35.148+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:44:35.147+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:44:35.279+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:44:35.279+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:44:35.367+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.596 seconds
[2024-01-31T13:45:06.216+0000] {processor.py:161} INFO - Started process (PID=1860) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:45:06.224+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:45:06.231+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:45:06.230+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:45:06.249+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:45:06.375+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:45:06.374+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:45:06.542+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:45:06.542+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:45:06.599+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.400 seconds
[2024-01-31T13:48:45.371+0000] {processor.py:161} INFO - Started process (PID=1889) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:48:45.514+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:48:45.609+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:48:45.516+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:49:30.338+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:56:58.040+0000] {processor.py:161} INFO - Started process (PID=1942) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:56:58.045+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:56:58.046+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:56:58.046+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:56:58.057+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:56:58.327+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:56:58.326+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:56:58.368+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:56:58.367+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:56:58.421+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.387 seconds
[2024-01-31T13:57:28.616+0000] {processor.py:161} INFO - Started process (PID=1995) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:57:28.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:57:28.624+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:57:28.624+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:57:28.638+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:57:28.681+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:57:28.680+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:57:28.727+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:57:28.726+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:57:28.762+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.154 seconds
[2024-01-31T13:57:59.302+0000] {processor.py:161} INFO - Started process (PID=2048) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:57:59.304+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:57:59.305+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:57:59.305+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:57:59.319+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:57:59.391+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:57:59.390+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:57:59.489+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:57:59.488+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:57:59.542+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.251 seconds
[2024-01-31T13:58:30.032+0000] {processor.py:161} INFO - Started process (PID=2103) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:58:30.037+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:58:30.040+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:58:30.039+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:58:30.068+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:58:30.172+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:58:30.171+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:58:30.254+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:58:30.253+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:58:30.350+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.327 seconds
[2024-01-31T13:59:00.457+0000] {processor.py:161} INFO - Started process (PID=2159) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:59:00.461+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:59:00.463+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:59:00.463+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:59:00.475+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:59:00.514+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:59:00.513+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:59:00.558+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:59:00.557+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:59:00.596+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.150 seconds
[2024-01-31T13:59:30.859+0000] {processor.py:161} INFO - Started process (PID=2215) to work on /opt/airflow/dags/prueba.py
[2024-01-31T13:59:30.861+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T13:59:30.863+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:59:30.862+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T13:59:30.877+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T13:59:30.942+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:59:30.941+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T13:59:31.028+0000] {logging_mixin.py:188} INFO - [2024-01-31T13:59:31.027+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T13:59:31.097+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.245 seconds
[2024-01-31T14:00:01.227+0000] {processor.py:161} INFO - Started process (PID=2272) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:00:01.228+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:00:01.230+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:00:01.229+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:00:01.243+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:00:01.288+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:00:01.287+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T14:00:01.383+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:00:01.383+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T14:00:01.443+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.224 seconds
[2024-01-31T14:00:31.481+0000] {processor.py:161} INFO - Started process (PID=2321) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:00:31.483+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:00:31.485+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:00:31.484+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:00:31.495+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:00:31.569+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:00:31.568+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T14:00:31.642+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:00:31.641+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T14:00:31.697+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.221 seconds
[2024-01-31T14:01:02.106+0000] {processor.py:161} INFO - Started process (PID=2377) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:01:02.108+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:01:02.110+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:01:02.109+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:01:02.124+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:01:02.184+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:01:02.183+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T14:01:02.277+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:01:02.276+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T14:01:02.323+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.225 seconds
[2024-01-31T14:01:32.474+0000] {processor.py:161} INFO - Started process (PID=2430) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:01:32.484+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:01:32.486+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:01:32.485+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:01:32.500+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:01:32.546+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:01:32.546+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T14:01:32.600+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:01:32.599+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T14:01:32.658+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.195 seconds
[2024-01-31T14:02:02.695+0000] {processor.py:161} INFO - Started process (PID=2485) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:02:02.697+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:02:02.699+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:02:02.698+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:02:02.710+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:02:02.752+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:02:02.752+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T14:02:02.831+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:02:02.830+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T14:02:02.925+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.236 seconds
[2024-01-31T14:02:33.193+0000] {processor.py:161} INFO - Started process (PID=2540) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:02:33.198+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:02:33.200+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:02:33.200+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:02:33.226+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:02:33.314+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:02:33.313+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T14:02:33.380+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:02:33.379+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T14:02:33.454+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.273 seconds
[2024-01-31T14:03:03.667+0000] {processor.py:161} INFO - Started process (PID=2593) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:03:03.669+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:03:03.671+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:03:03.670+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:03:03.683+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:03:03.733+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:03:03.733+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T14:03:03.798+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:03:03.797+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T14:03:04.105+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.445 seconds
[2024-01-31T14:03:34.670+0000] {processor.py:161} INFO - Started process (PID=2649) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:03:34.672+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:03:34.675+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:03:34.674+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:03:34.692+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:03:34.739+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:03:34.738+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T14:03:34.803+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:03:34.802+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T14:03:34.868+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.203 seconds
[2024-01-31T14:04:05.150+0000] {processor.py:161} INFO - Started process (PID=2705) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:04:05.152+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:04:05.154+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:04:05.153+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:04:05.167+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:04:05.213+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:04:05.212+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T14:04:05.288+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:04:05.286+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T14:04:05.350+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.207 seconds
[2024-01-31T14:04:35.883+0000] {processor.py:161} INFO - Started process (PID=2761) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:04:35.885+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:04:35.887+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:04:35.886+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:04:35.897+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:04:35.936+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:04:35.935+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T14:04:35.994+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:04:35.993+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T14:04:36.035+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.159 seconds
[2024-01-31T14:05:06.743+0000] {processor.py:161} INFO - Started process (PID=2817) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:05:06.746+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:05:06.748+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:05:06.747+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:05:06.760+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:05:07.052+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:05:07.051+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T14:05:07.108+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:05:07.107+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T14:05:07.164+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.428 seconds
[2024-01-31T14:05:37.550+0000] {processor.py:161} INFO - Started process (PID=2872) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:05:37.551+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:05:37.554+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:05:37.553+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:05:37.570+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:05:37.623+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:05:37.623+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T14:05:37.694+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:05:37.694+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T14:05:37.740+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.200 seconds
[2024-01-31T14:06:08.388+0000] {processor.py:161} INFO - Started process (PID=2928) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:06:08.395+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:06:08.402+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:06:08.399+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:06:08.426+0000] {processor.py:840} INFO - DAG(s) 'hola_mundo' retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:06:08.512+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:06:08.512+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-01-31T14:06:08.598+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:06:08.597+0000] {dag.py:3823} INFO - Setting next_dagrun for hola_mundo to 2024-01-31 00:00:00+00:00, run_after=2024-02-01 00:00:00+00:00
[2024-01-31T14:06:08.676+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.299 seconds
[2024-01-31T14:14:28.526+0000] {processor.py:161} INFO - Started process (PID=49) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:14:28.529+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:14:28.545+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:14:28.544+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:14:28.570+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:14:28.567+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:14:28.570+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:14:28.637+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.119 seconds
[2024-01-31T14:14:58.821+0000] {processor.py:161} INFO - Started process (PID=105) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:14:58.824+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:14:58.831+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:14:58.830+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:14:58.860+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:14:58.844+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:14:58.860+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:14:58.914+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.102 seconds
[2024-01-31T14:15:29.109+0000] {processor.py:161} INFO - Started process (PID=161) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:15:29.111+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:15:29.112+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:15:29.111+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:15:29.116+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:15:29.115+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:15:29.118+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:15:29.155+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.054 seconds
[2024-01-31T14:15:59.254+0000] {processor.py:161} INFO - Started process (PID=217) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:15:59.257+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:15:59.260+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:15:59.259+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:15:59.266+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:15:59.264+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:15:59.267+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:15:59.303+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.057 seconds
[2024-01-31T14:16:29.954+0000] {processor.py:161} INFO - Started process (PID=273) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:16:30.001+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:16:30.003+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:16:30.002+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:16:30.036+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:16:30.021+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:16:30.037+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:16:30.304+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.370 seconds
[2024-01-31T14:17:05.146+0000] {processor.py:161} INFO - Started process (PID=329) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:17:05.271+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:17:05.318+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:17:05.273+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:17:05.711+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:17:05.693+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:17:05.712+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:17:06.341+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 1.263 seconds
[2024-01-31T14:17:43.494+0000] {processor.py:161} INFO - Started process (PID=383) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:17:43.501+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:17:43.510+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:17:43.503+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:17:43.541+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:17:43.532+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:17:43.543+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:17:43.608+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.133 seconds
[2024-01-31T14:18:13.728+0000] {processor.py:161} INFO - Started process (PID=438) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:18:13.735+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:18:13.737+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:18:13.736+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:18:13.749+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:18:13.745+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:18:13.750+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:18:13.791+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.074 seconds
[2024-01-31T14:18:43.982+0000] {processor.py:161} INFO - Started process (PID=489) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:18:43.988+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:18:43.991+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:18:43.990+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:18:44.008+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:18:44.001+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:18:44.009+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:18:44.084+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.110 seconds
[2024-01-31T14:19:14.312+0000] {processor.py:161} INFO - Started process (PID=543) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:19:14.315+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:19:14.317+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:19:14.316+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:19:14.337+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:19:14.335+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:19:14.338+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:19:14.386+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.088 seconds
[2024-01-31T14:19:44.836+0000] {processor.py:161} INFO - Started process (PID=599) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:19:44.841+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:19:44.843+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:19:44.842+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:19:44.856+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:19:44.852+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:19:44.858+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:19:44.916+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.089 seconds
[2024-01-31T14:20:03.227+0000] {processor.py:161} INFO - Started process (PID=632) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:20:03.312+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:20:03.317+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:20:03.316+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:20:03.355+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:20:03.343+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:20:03.356+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:20:03.409+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.195 seconds
[2024-01-31T14:20:34.107+0000] {processor.py:161} INFO - Started process (PID=686) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:20:34.175+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:20:34.188+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:20:34.186+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:20:34.249+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:20:34.233+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:20:34.250+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:20:34.329+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.254 seconds
[2024-01-31T14:20:48.996+0000] {processor.py:161} INFO - Started process (PID=719) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:20:48.998+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:20:49.000+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:20:48.999+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:20:49.007+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:20:49.006+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:20:49.008+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:20:49.042+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.053 seconds
[2024-01-31T14:21:19.498+0000] {processor.py:161} INFO - Started process (PID=770) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:21:19.501+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:21:19.503+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:21:19.502+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:21:19.516+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:21:19.512+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:21:19.517+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:21:19.581+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.092 seconds
[2024-01-31T14:21:50.364+0000] {processor.py:161} INFO - Started process (PID=826) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:21:50.367+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:21:50.370+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:21:50.369+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:21:50.382+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:21:50.379+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:21:50.383+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:21:50.429+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.075 seconds
[2024-01-31T14:22:20.716+0000] {processor.py:161} INFO - Started process (PID=883) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:22:20.721+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:22:20.723+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:22:20.722+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:22:20.734+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:22:20.729+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:22:20.735+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:22:20.786+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.076 seconds
[2024-01-31T14:22:51.519+0000] {processor.py:161} INFO - Started process (PID=939) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:22:51.524+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:22:51.527+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:22:51.526+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:22:51.542+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:22:51.533+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:22:51.543+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:22:51.580+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.068 seconds
[2024-01-31T14:23:21.984+0000] {processor.py:161} INFO - Started process (PID=995) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:23:21.986+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:23:21.989+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:23:21.988+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:23:22.004+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:23:22.001+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:23:22.005+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:23:22.058+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.079 seconds
[2024-01-31T14:23:52.860+0000] {processor.py:161} INFO - Started process (PID=1051) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:23:52.884+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:23:52.886+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:23:52.886+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:23:52.896+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:23:52.893+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:23:52.897+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:23:52.941+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.091 seconds
[2024-01-31T14:24:23.202+0000] {processor.py:161} INFO - Started process (PID=1107) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:24:23.206+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:24:23.207+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:24:23.207+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:24:23.214+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:24:23.212+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:24:23.215+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:24:23.265+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.069 seconds
[2024-01-31T14:24:53.772+0000] {processor.py:161} INFO - Started process (PID=1163) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:24:53.774+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:24:53.777+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:24:53.776+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:24:53.784+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:24:53.781+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:24:53.785+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:24:53.821+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.055 seconds
[2024-01-31T14:25:23.943+0000] {processor.py:161} INFO - Started process (PID=1217) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:25:23.950+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:25:23.953+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:25:23.952+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:25:23.968+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:25:23.959+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:25:23.970+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:25:24.031+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.118 seconds
[2024-01-31T14:25:54.075+0000] {processor.py:161} INFO - Started process (PID=1271) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:25:54.078+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:25:54.081+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:25:54.079+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:25:54.092+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:25:54.088+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:25:54.093+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:25:54.150+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.083 seconds
[2024-01-31T14:26:24.373+0000] {processor.py:161} INFO - Started process (PID=1326) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:26:24.374+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:26:24.377+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:26:24.376+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:26:24.398+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:26:24.394+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:26:24.399+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:26:24.460+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.098 seconds
[2024-01-31T14:26:54.650+0000] {processor.py:161} INFO - Started process (PID=1380) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:26:54.657+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:26:54.660+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:26:54.659+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:26:54.677+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:26:54.668+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:26:54.677+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:26:54.712+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.070 seconds
[2024-01-31T14:27:25.460+0000] {processor.py:161} INFO - Started process (PID=1436) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:27:25.464+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:27:25.468+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:27:25.465+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:27:25.479+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:27:25.475+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:27:25.479+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:27:25.545+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.093 seconds
[2024-01-31T14:27:56.288+0000] {processor.py:161} INFO - Started process (PID=1493) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:27:56.301+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:27:56.304+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:27:56.303+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:27:56.322+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:27:56.318+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:27:56.323+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:27:56.376+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.096 seconds
[2024-01-31T14:28:26.598+0000] {processor.py:161} INFO - Started process (PID=1549) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:28:26.601+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:28:26.604+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:28:26.603+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:28:26.615+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:28:26.611+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:28:26.617+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:28:26.683+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.094 seconds
[2024-01-31T14:28:56.851+0000] {processor.py:161} INFO - Started process (PID=1605) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:28:56.852+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:28:56.854+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:28:56.853+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:28:56.860+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:28:56.858+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:28:56.861+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:28:56.906+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.081 seconds
[2024-01-31T14:29:27.231+0000] {processor.py:161} INFO - Started process (PID=1661) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:29:27.244+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:29:27.247+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:29:27.246+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:29:27.260+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:29:27.257+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:29:27.260+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:29:27.298+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.074 seconds
[2024-01-31T14:29:57.847+0000] {processor.py:161} INFO - Started process (PID=1717) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:29:57.862+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:29:57.865+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:29:57.864+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:29:57.879+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:29:57.872+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:29:57.880+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:29:57.930+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.091 seconds
[2024-01-31T14:30:28.315+0000] {processor.py:161} INFO - Started process (PID=1773) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:30:28.339+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:30:28.346+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:30:28.346+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:30:28.370+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:30:28.363+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:30:28.372+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:30:28.450+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.143 seconds
[2024-01-31T14:30:59.311+0000] {processor.py:161} INFO - Started process (PID=1829) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:30:59.313+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:30:59.317+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:30:59.316+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:30:59.338+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:30:59.327+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:30:59.339+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:30:59.390+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.086 seconds
[2024-01-31T14:31:29.463+0000] {processor.py:161} INFO - Started process (PID=1885) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:31:29.466+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:31:29.468+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:31:29.467+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:31:29.504+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:31:29.490+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:31:29.505+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:31:29.567+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.112 seconds
[2024-01-31T14:32:38.514+0000] {processor.py:161} INFO - Started process (PID=1933) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:32:38.518+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:32:38.521+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:32:38.520+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:32:38.540+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:32:38.531+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:32:38.541+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:32:38.615+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.115 seconds
[2024-01-31T14:33:09.365+0000] {processor.py:161} INFO - Started process (PID=1987) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:33:09.370+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:33:09.372+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:33:09.372+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:33:09.418+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:33:09.398+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:33:09.419+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:33:09.503+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.155 seconds
[2024-01-31T14:33:39.536+0000] {processor.py:161} INFO - Started process (PID=2041) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:33:39.539+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:33:39.540+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:33:39.540+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:33:39.547+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:33:39.545+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:33:39.548+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:33:39.588+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.058 seconds
[2024-01-31T14:34:10.207+0000] {processor.py:161} INFO - Started process (PID=2095) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:34:10.214+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:34:10.216+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:34:10.215+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:34:10.226+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:34:10.223+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:34:10.227+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:34:10.281+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.084 seconds
[2024-01-31T14:34:40.653+0000] {processor.py:161} INFO - Started process (PID=2151) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:34:40.666+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:34:40.668+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:34:40.667+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:34:40.703+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:34:40.685+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:34:40.704+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:34:40.843+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.199 seconds
[2024-01-31T14:35:11.251+0000] {processor.py:161} INFO - Started process (PID=2207) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:35:11.253+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:35:11.255+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:35:11.254+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:35:11.267+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:35:11.261+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:35:11.268+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:35:11.311+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.071 seconds
[2024-01-31T14:35:42.066+0000] {processor.py:161} INFO - Started process (PID=2263) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:35:42.071+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:35:42.074+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:35:42.073+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:35:42.102+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:35:42.086+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:35:42.103+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:35:42.211+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.155 seconds
[2024-01-31T14:36:12.332+0000] {processor.py:161} INFO - Started process (PID=2319) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:36:12.335+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:36:12.337+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:36:12.336+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:36:12.347+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:36:12.343+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:36:12.348+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:36:12.402+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.082 seconds
[2024-01-31T14:36:42.861+0000] {processor.py:161} INFO - Started process (PID=2375) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:36:42.892+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:36:42.894+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:36:42.893+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:36:42.912+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:36:42.906+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:36:42.913+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:36:42.998+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.194 seconds
[2024-01-31T14:37:13.200+0000] {processor.py:161} INFO - Started process (PID=2431) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:37:13.203+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:37:13.205+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:37:13.204+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:37:13.213+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:37:13.210+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:37:13.213+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:37:13.247+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.054 seconds
[2024-01-31T14:37:43.329+0000] {processor.py:161} INFO - Started process (PID=2487) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:37:43.333+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:37:43.335+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:37:43.334+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:37:43.345+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:37:43.340+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:37:43.346+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:37:43.381+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.063 seconds
[2024-01-31T14:42:31.236+0000] {processor.py:161} INFO - Started process (PID=2543) to work on /opt/airflow/dags/prueba.py
[2024-01-31T14:42:31.244+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/prueba.py for tasks to queue
[2024-01-31T14:42:31.246+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:42:31.246+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/prueba.py
[2024-01-31T14:42:31.277+0000] {logging_mixin.py:188} INFO - [2024-01-31T14:42:31.267+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/prueba.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/prueba.py", line 9, in <module>
    from airflow.operators.branch_operator import BranchPythonOperator
ImportError: cannot import name 'BranchPythonOperator' from 'airflow.operators.branch_operator' (unknown location)
[2024-01-31T14:42:31.278+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/prueba.py
[2024-01-31T14:42:32.914+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/prueba.py took 0.984 seconds
