[2024-01-30T11:45:00.977+0000] {scheduler_job_runner.py:1586} WARNING - Marking task instance <TaskInstance: example_bash_operator.this_will_skip scheduled__2024-01-29T00:00:00+00:00 [queued]> stuck in queued as failed. If the task instance has available retries, it will be retried.
[2024-01-30T11:45:03.047+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: example_bash_operator.this_will_skip scheduled__2024-01-29T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
